package com.openmason.engine.cearl;

import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * The GLSL backend. One byte-exact golden pins the whole emission shape
 * (header, SSBO blocks, uniform, builtin mapping, literal typing, formatting);
 * the remaining tests pin the constructs the golden doesn't reach.
 */
class GlslEmitterTest {

    private static String emit(String source, String kernel) {
        return CearlCompiler.compile(source, "emit.CEARL", Map.of("vram", 0L))
            .kernel(kernel).glsl();
    }

    @Test
    void goldenKernel() {
        String glsl = emit("""
            kernel scale_add(32)
                take src: f32[] in
                take dst: f32[] out
                take k: f32

                fix i = gid.x
                if i < count(src)
                    dst[i] = src[i] * k + 1.0
                end
            end
            """, "scale_add");

        String golden = """
            #version 430 core
            // Generated by CEARL from kernel 'scale_add' — do not edit.
            layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

            layout(std430, binding = 0) readonly buffer cearl_src { float src[]; };
            layout(std430, binding = 1) writeonly buffer cearl_dst { float dst[]; };
            uniform float k;

            void main() {
                uint i = gl_GlobalInvocationID.x;
                if ((i < uint(src.length()))) {
                    dst[i] = ((src[i] * k) + 1.0);
                }
            }
            """;
        assertEquals(golden, glsl);
    }

    @Test
    void intLiteralsCarryTheirCoercedSpelling() {
        String glsl = emit("""
            kernel k
                take r: f32[] out
                take n: u32[] inout
                r[gid.x] = 2 * 1.5
                atomic_add(n[0], 3)
            end
            """, "k");
        assertTrue(glsl.contains("(2.0 * 1.5)"), glsl);         // literal adapted to f32
        assertTrue(glsl.contains("atomicAdd(n[0], 3u)"), glsl); // value adapted to uint
    }

    @Test
    void controlFlowLowersDirectly() {
        String glsl = emit("""
            kernel k
                take r: i32[] out
                flux total = 0
                for j in 0..10
                    if j == 5
                        continue
                    elif j == 8
                        break
                    end
                    total = total + j
                end
                while total > 100
                    total = total - 1
                end
                r[0] = total
            end
            """, "k");
        assertTrue(glsl.contains("for (int j = 0; j < 10; ++j) {"), glsl);
        assertTrue(glsl.contains("} else if ((j == 8)) {"), glsl);
        assertTrue(glsl.contains("while ((total > 100)) {"), glsl);
    }

    @Test
    void wordedLogicLowersToSymbols() {
        String glsl = emit("""
            kernel k
                take r: u32[] out
                fix a = gid.x > 1 and gid.x < 10
                fix b = not a or gid.y == 0
                r[0] = u32(b)
            end
            """, "k");
        assertTrue(glsl.contains("((gl_GlobalInvocationID.x > 1u) && (gl_GlobalInvocationID.x < 10u))"), glsl);
        assertTrue(glsl.contains("((!a) || (gl_GlobalInvocationID.y == 0u))"), glsl);
    }

    @Test
    void formsEmitInDependencyOrder() {
        String glsl = emit("""
            form Outer
                inner: Inner
                w: f32
            end

            form Inner
                v: vec3
                pad: f32
            end

            kernel k
                take xs: Outer[] in
                take r: f32[] out
                r[gid.x] = xs[gid.x].inner.v.x
            end
            """, "k");
        int inner = glsl.indexOf("struct Inner");
        int outer = glsl.indexOf("struct Outer");
        assertTrue(inner >= 0 && outer > inner,
            "Inner must be defined before Outer:\n" + glsl);
    }

    @Test
    void sharedMemoryReductionCompilesAndEmits() {
        // The CUDA-shaped mechanic: workgroup-shared scratch + barrier() +
        // lid-indexed tree reduction, folding partial sums via one atomic.
        String glsl = emit("""
            kernel reduce_sum(256)
                take values: u32[] in
                take totals: u32[] inout
                shared scratch: u32[256]

                fix i = gid.x
                scratch[lid.x] = 0
                if i < count(values)
                    scratch[lid.x] = values[i]
                end
                barrier()
                flux stride: u32 = 128
                while stride > 0
                    if lid.x < stride
                        scratch[lid.x] = scratch[lid.x] + scratch[lid.x + stride]
                    end
                    barrier()
                    stride = stride / 2
                end
                if lid.x == 0
                    atomic_add(totals[0], scratch[0])
                end
            end
            """, "reduce_sum");
        assertTrue(glsl.contains("shared uint scratch[256];"), glsl);
        assertTrue(glsl.contains("barrier();"), glsl);
        assertTrue(glsl.contains("scratch[gl_LocalInvocationID.x]"), glsl);
        assertTrue(glsl.contains("atomicAdd(totals[0], scratch[0])"), glsl);
    }

    @Test
    void uniformArraysAndPickEmit() {
        String glsl = emit("""
            pin PLANES: i32 = 6

            kernel k
                take planes: vec4[PLANES]
                take r: f32[] out
                fix pl = planes[0]
                r[gid.x] = pick(pl.w > 0.0, pl.x, pl.y)
            end
            """, "k");
        assertTrue(glsl.contains("uniform vec4 planes[6];"), glsl);
        assertTrue(glsl.contains("((pl.w > 0.0) ? pl.x : pl.y)"), glsl);
    }

    @Test
    void pinsAndVecConstructorsEmit() {
        String glsl = emit("""
            pin SCALE: f32 = 2.5
            pin STEPS: u32 = 4

            kernel k
                take r: vec4[] out
                r[gid.x] = vec4(vec3(SCALE), f32(STEPS))
            end
            """, "k");
        assertTrue(glsl.contains("const float SCALE = 2.5;"), glsl);
        assertTrue(glsl.contains("const uint STEPS = 4u;"), glsl);
        assertTrue(glsl.contains("vec4(vec3(SCALE), float(STEPS))"), glsl);
    }
}
