package com.openmason.engine.cearl;

import com.openmason.engine.cearl.CearlAst.Assign;
import com.openmason.engine.cearl.CearlAst.Bin;
import com.openmason.engine.cearl.CearlAst.Block;
import com.openmason.engine.cearl.CearlAst.BoolLit;
import com.openmason.engine.cearl.CearlAst.Call;
import com.openmason.engine.cearl.CearlAst.Dir;
import com.openmason.engine.cearl.CearlAst.Expr;
import com.openmason.engine.cearl.CearlAst.ExprStmt;
import com.openmason.engine.cearl.CearlAst.FloatLit;
import com.openmason.engine.cearl.CearlAst.FnDecl;
import com.openmason.engine.cearl.CearlAst.ForRange;
import com.openmason.engine.cearl.CearlAst.Ident;
import com.openmason.engine.cearl.CearlAst.If;
import com.openmason.engine.cearl.CearlAst.Index;
import com.openmason.engine.cearl.CearlAst.IntLit;
import com.openmason.engine.cearl.CearlAst.KernelDecl;
import com.openmason.engine.cearl.CearlAst.Let;
import com.openmason.engine.cearl.CearlAst.Member;
import com.openmason.engine.cearl.CearlAst.Param;
import com.openmason.engine.cearl.CearlAst.Return;
import com.openmason.engine.cearl.CearlAst.Stmt;
import com.openmason.engine.cearl.CearlAst.StructDecl;
import com.openmason.engine.cearl.CearlAst.Un;
import com.openmason.engine.cearl.CearlAst.While;
import com.openmason.engine.cearl.CearlChecker.Checked;
import com.openmason.engine.cearl.CearlChecker.ConstInfo;
import com.openmason.engine.cearl.CearlChecker.FnInfo;
import com.openmason.engine.cearl.CearlChecker.StructInfo;
import com.openmason.engine.cearl.CearlType.PrimKind;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Lowers a checked CEARL kernel to GLSL 430 compute source. The mapping is
 * deliberately direct — one CEARL construct, one GLSL construct — so the
 * generated source stays readable when a driver error points into it:
 *
 * <ul>
 *   <li>buffer params → std430 SSBO blocks, {@code readonly}/{@code writeonly}
 *       by direction, bound in declaration order
 *   <li>scalar/vector params → uniforms
 *   <li>struct methods → free functions named {@code Struct_method} taking
 *       {@code self} first ({@code inout} only when the method mutates it)
 *   <li>{@code gid}/{@code lid}/{@code wgid}/{@code nwg} →
 *       {@code gl_GlobalInvocationID} and friends
 *   <li>{@code len(buf)} → {@code uint(buf.length())},
 *       {@code atomic_add} → {@code atomicAdd}, casts → GLSL constructors
 * </ul>
 *
 * <p>Every binary expression is parenthesized — noisier than precedence-aware
 * emission, but the output can never disagree with CEARL's own precedence.
 */
final class GlslEmitter {

    private final Checked checked;
    private final StringBuilder out = new StringBuilder();
    private int indent;

    private GlslEmitter(Checked checked) {
        this.checked = checked;
    }

    static CearlKernel emit(Checked checked, KernelDecl kernel) {
        return new GlslEmitter(checked).run(kernel);
    }

    private CearlKernel run(KernelDecl kernel) {
        List<CearlKernel.BufferBinding> buffers = new ArrayList<>();
        List<CearlKernel.UniformBinding> uniforms = new ArrayList<>();

        line("#version 430 core");
        line("// Generated by CEARL from kernel '" + kernel.name() + "' — do not edit.");
        line("layout(local_size_x = " + kernel.localSize()
            + ", local_size_y = 1, local_size_z = 1) in;");
        blank();

        emitStructs();
        emitConsts();

        int binding = 0;
        for (Param p : kernel.params()) {
            if (p.type().array() && p.type().size() == null) {
                String elem = glslTypeName(p.type().name());
                String qualifier = switch (p.dir()) {
                    case IN -> "readonly ";
                    case OUT -> "writeonly ";
                    case INOUT -> "";
                };
                line("layout(std430, binding = " + binding + ") " + qualifier
                    + "buffer cearl_" + p.name() + " { " + elem + " " + p.name() + "[]; };");
                buffers.add(new CearlKernel.BufferBinding(p.name(), p.dir(), elem, binding));
                binding++;
            } else if (p.type().array()) {
                // Sized take = uniform array (register space).
                String elem = glslTypeName(p.type().name());
                int size = checked.resolvedSizes().get(p).intValue();
                line("uniform " + elem + " " + p.name() + "[" + size + "];");
                uniforms.add(new CearlKernel.UniformBinding(p.name(), elem, size));
            } else {
                String type = glslTypeName(p.type().name());
                line("uniform " + type + " " + p.name() + ";");
                uniforms.add(new CearlKernel.UniformBinding(p.name(), type, 0));
            }
        }
        for (CearlAst.SharedDecl sh : kernel.shareds()) {
            line("shared " + glslTypeName(sh.type().name()) + " " + sh.name()
                + "[" + checked.resolvedSizes().get(sh) + "];");
        }
        if (!kernel.params().isEmpty() || !kernel.shareds().isEmpty()) {
            blank();
        }

        emitFunctions();

        line("void main() {");
        indent++;
        emitBlockStmts(kernel.body());
        indent--;
        line("}");

        return new CearlKernel(kernel.name(), kernel.localSize(), buffers, uniforms,
            out.toString());
    }

    /** GLSL spelling for a syntactic type name (builtin or struct). */
    private static String glslTypeName(String name) {
        CearlType t = CearlType.builtin(name);
        return t != null ? t.glslName() : name;
    }

    // ─── Declarations ─────────────────────────────────────────────────────

    private void emitStructs() {
        // Dependency order: a struct's field structs come first.
        Set<String> emitted = new LinkedHashSet<>();
        for (String name : checked.structs().keySet()) {
            emitStructDeps(name, emitted);
        }
        if (!checked.structs().isEmpty()) {
            blank();
        }
    }

    private void emitStructDeps(String name, Set<String> emitted) {
        if (emitted.contains(name)) {
            return;
        }
        StructInfo info = checked.structs().get(name);
        for (CearlType t : info.fields().values()) {
            if (t instanceof CearlType.Struct s) {
                emitStructDeps(s.name(), emitted);
            }
        }
        emitted.add(name);
        line("struct " + name + " {");
        indent++;
        for (Map.Entry<String, CearlType> f : info.fields().entrySet()) {
            line(f.getValue().glslName() + " " + f.getKey() + ";");
        }
        indent--;
        line("};");
    }

    private void emitConsts() {
        boolean any = false;
        for (Map.Entry<String, ConstInfo> e : checked.consts().entrySet()) {
            ConstInfo c = e.getValue();
            if (c.type().is(PrimKind.I64)) {
                continue; // Host-only; the checker bans device references.
            }
            line("const " + c.type().glslName() + " " + e.getKey() + " = "
                + constLiteral(c) + ";");
            any = true;
        }
        if (any) {
            blank();
        }
    }

    private static String constLiteral(ConstInfo c) {
        Object v = c.value();
        if (v instanceof Boolean b) {
            return b.toString();
        }
        if (c.type().is(PrimKind.F32)) {
            double d = v instanceof Long l ? (double) l : (Double) v;
            return floatText(d);
        }
        if (c.type().is(PrimKind.U32)) {
            return v + "u";
        }
        return v.toString();
    }

    private void emitFunctions() {
        // Prototypes first so definition order never matters.
        List<Runnable> definitions = new ArrayList<>();
        boolean any = false;
        for (StructInfo s : checked.structs().values()) {
            for (FnInfo m : s.methods().values()) {
                line(fnSignature(m) + ";");
                definitions.add(() -> emitFnDefinition(m));
                any = true;
            }
        }
        for (FnInfo f : checked.fns().values()) {
            line(fnSignature(f) + ";");
            definitions.add(() -> emitFnDefinition(f));
            any = true;
        }
        if (any) {
            blank();
            for (Runnable def : definitions) {
                def.run();
                blank();
            }
        }
    }

    private String fnSignature(FnInfo info) {
        FnDecl f = info.decl();
        StringBuilder sig = new StringBuilder();
        sig.append(info.ret().is(PrimKind.VOID) ? "void" : info.ret().glslName());
        sig.append(' ').append(fnGlslName(info)).append('(');
        List<String> params = new ArrayList<>();
        if (f.owner() != null) {
            params.add((info.mutatesSelf() ? "inout " : "in ") + f.owner() + " self");
        }
        for (int i = 0; i < f.params().size(); i++) {
            params.add("in " + info.paramTypes().get(i).glslName() + " " + f.params().get(i).name());
        }
        sig.append(String.join(", ", params)).append(')');
        return sig.toString();
    }

    private static String fnGlslName(FnInfo info) {
        FnDecl f = info.decl();
        return f.owner() == null ? f.name() : f.owner() + "_" + f.name();
    }

    private void emitFnDefinition(FnInfo info) {
        line(fnSignature(info) + " {");
        indent++;
        emitBlockStmts(info.decl().body());
        indent--;
        line("}");
    }

    // ─── Statements ───────────────────────────────────────────────────────

    private void emitBlockStmts(Block block) {
        for (Stmt s : block.stmts()) {
            emitStmt(s);
        }
    }

    private void emitStmt(Stmt stmt) {
        switch (stmt) {
            case Block b -> {
                line("{");
                indent++;
                emitBlockStmts(b);
                indent--;
                line("}");
            }
            case Let l -> {
                CearlType t = checked.typeOf(l.init());
                line(t.glslName() + " " + l.name() + " = " + expr(l.init()) + ";");
            }
            case Assign a -> line(expr(a.target()) + " " + a.op() + " " + expr(a.value()) + ";");
            case If i -> emitIf(i);
            case While w -> {
                line("while (" + expr(w.cond()) + ") {");
                indent++;
                emitBlockStmts(w.body());
                indent--;
                line("}");
            }
            case ForRange f -> {
                String t = checked.typeOf(f.from()).glslName();
                line("for (" + t + " " + f.var() + " = " + expr(f.from()) + "; "
                    + f.var() + " < " + expr(f.to()) + "; ++" + f.var() + ") {");
                indent++;
                emitBlockStmts(f.body());
                indent--;
                line("}");
            }
            case Return r -> line(r.value() == null ? "return;" : "return " + expr(r.value()) + ";");
            case CearlAst.Break b -> line("break;");
            case CearlAst.Continue c -> line("continue;");
            case ExprStmt e -> line(expr(e.expr()) + ";");
        }
    }

    private void emitIf(If i) {
        line("if (" + expr(i.cond()) + ") {");
        indent++;
        emitBlockStmts(i.then());
        indent--;
        if (i.elseBranch() == null) {
            line("}");
        } else if (i.elseBranch() instanceof If elif) {
            lineNoBreak("} else ");
            emitIfContinued(elif);
        } else {
            line("} else {");
            indent++;
            emitBlockStmts((Block) i.elseBranch());
            indent--;
            line("}");
        }
    }

    /** Emits an else-if without re-indenting (continues the previous line). */
    private void emitIfContinued(If i) {
        out.append("if (").append(expr(i.cond())).append(") {\n");
        indent++;
        emitBlockStmts(i.then());
        indent--;
        if (i.elseBranch() == null) {
            line("}");
        } else if (i.elseBranch() instanceof If elif) {
            lineNoBreak("} else ");
            emitIfContinued(elif);
        } else {
            line("} else {");
            indent++;
            emitBlockStmts((Block) i.elseBranch());
            indent--;
            line("}");
        }
    }

    // ─── Expressions ──────────────────────────────────────────────────────

    private String expr(Expr e) {
        return switch (e) {
            case IntLit i -> intLiteral(i);
            case FloatLit f -> floatText(f.value());
            case BoolLit b -> Boolean.toString(b.value());
            case Ident id -> identName(id);
            case Member m -> expr(m.target()) + "." + m.name();
            case Index ix -> expr(ix.target()) + "[" + expr(ix.index()) + "]";
            case Un u -> "(" + u.op() + expr(u.operand()) + ")";
            case Bin b -> "(" + expr(b.left()) + " " + b.op() + " " + expr(b.right()) + ")";
            case Call c -> call(c);
            case CearlAst.SizeLit s -> throw new IllegalStateException(
                "size literal survived checking — checker bug");
        };
    }

    private String intLiteral(IntLit i) {
        CearlType t = checked.typeOf(i);
        if (t != null) {
            if (t.is(PrimKind.F32)) {
                return floatText(i.value());
            }
            if (t.is(PrimKind.U32)) {
                return i.value() + "u";
            }
        }
        return Long.toString(i.value());
    }

    private static String floatText(double d) {
        if (d == Math.floor(d) && !Double.isInfinite(d) && Math.abs(d) < 1e15) {
            return (long) d + ".0";
        }
        String s = Double.toString(d);
        // Java prints exponents as 1.0E-5; GLSL wants 1.0e-5.
        return s.replace("E", "e");
    }

    private String identName(Ident id) {
        // A bare field inside a method is sugar for self.<field>.
        if (checked.isImplicitSelf(id)) {
            return "self." + id.name();
        }
        return switch (id.name()) {
            case "gid" -> "gl_GlobalInvocationID";
            case "lid" -> "gl_LocalInvocationID";
            case "wgid" -> "gl_WorkGroupID";
            case "nwg" -> "gl_NumWorkGroups";
            default -> id.name();
        };
    }

    private String call(Call c) {
        if (c.callee() instanceof Member m) {
            // Method call: Owner_method(receiver, args...).
            CearlType receiver = checked.typeOf(m.target());
            String owner = ((CearlType.Struct) receiver).name();
            List<String> args = new ArrayList<>();
            args.add(expr(m.target()));
            for (Expr a : c.args()) {
                args.add(expr(a));
            }
            return owner + "_" + m.name() + "(" + String.join(", ", args) + ")";
        }
        String name = ((Ident) c.callee()).name();
        List<String> args = new ArrayList<>();
        for (Expr a : c.args()) {
            args.add(expr(a));
        }
        String joined = String.join(", ", args);
        return switch (name) {
            case "count" -> "uint(" + args.getFirst() + ".length())";
            case "pick" -> "(" + args.getFirst() + " ? " + args.get(1) + " : "
                + args.get(2) + ")";
            case "atomic_add" -> "atomicAdd(" + joined + ")";
            case "atomic_min" -> "atomicMin(" + joined + ")";
            case "atomic_max" -> "atomicMax(" + joined + ")";
            case "f32" -> "float(" + joined + ")";
            case "i32" -> "int(" + joined + ")";
            case "u32" -> "uint(" + joined + ")";
            default -> name + "(" + joined + ")";
        };
    }

    // ─── Output plumbing ──────────────────────────────────────────────────

    private void line(String text) {
        out.append("    ".repeat(indent)).append(text).append('\n');
    }

    private void lineNoBreak(String text) {
        out.append("    ".repeat(indent)).append(text);
    }

    private void blank() {
        out.append('\n');
    }
}
