package com.stonebreak.rendering.models.entities;

import org.lwjgl.opengl.GL11;

import java.nio.ByteBuffer;

/**
 * Factory for the 1x1 nearest-filtered RGBA textures the simple-cube entity
 * paths use as flat tints (fallback white, arrow brown, emissive bolt/spike/zone
 * colours). Replaces the per-colour copy-pasted creators that used to live in
 * {@link EntityRenderer}; {@link #pixel} is the pure, GL-free part so the
 * generated bytes can be unit-tested.
 */
public final class SolidColorTexture {

    private SolidColorTexture() {
    }

    /**
     * The single RGBA8 pixel for a colour, exactly as uploaded by {@link #create}:
     * a 4-byte direct buffer, flipped and ready to read.
     */
    public static ByteBuffer pixel(int r, int g, int b, int a) {
        ByteBuffer pixel = ByteBuffer.allocateDirect(4);
        pixel.put((byte) r).put((byte) g).put((byte) b).put((byte) a).flip();
        return pixel;
    }

    /**
     * Generates and uploads a 1x1 GL_RGBA texture of the given colour with
     * nearest min/mag filtering. Leaves the 2D texture binding at 0 afterwards.
     *
     * @return the GL texture name
     */
    public static int create(int r, int g, int b, int a) {
        int texture = GL11.glGenTextures();
        GL11.glBindTexture(GL11.GL_TEXTURE_2D, texture);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
        GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
        GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL11.GL_RGBA, 1, 1, 0,
                GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, pixel(r, g, b, a));
        GL11.glBindTexture(GL11.GL_TEXTURE_2D, 0);
        return texture;
    }

    /** Deletes a texture created by {@link #create}; a 0 handle is a no-op. */
    public static void delete(int texture) {
        if (texture != 0) {
            GL11.glDeleteTextures(texture);
        }
    }
}
