package com.stonebreak.world.generation;

import com.stonebreak.blocks.BlockType;
import com.stonebreak.world.chunk.Chunk;
import com.stonebreak.world.generation.diffusion.CliffTileSource;
import com.stonebreak.world.generation.heightmap.CliffExposure;
import com.stonebreak.world.generation.heightmap.HeightMapGenerator;
import com.stonebreak.world.operations.WorldConfiguration;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A carved cliff opening must lead somewhere.
 *
 * <p>Openings themselves were never the problem — {@code Density3D.solidInOverhangBand} cuts
 * them well and this test does not touch it. What was wrong is what sat behind one. The
 * overhang band used to <em>replace</em> the cave test in the top 16 blocks of a column, so no
 * chamber or tunnel could exist there, and immediately below it lies the depth 10-35 shell that
 * the cheese spline and the spaghetti fade both leave solid. An opening was a pocket in a skin
 * with a wall at the back: 2-4 blocks deep, and the cave network it should have led to started
 * some 35 blocks further in than a player could ever get.
 *
 * <p>Two things have to hold at once, and either alone is easy to get by breaking the other:
 *
 * <ul>
 *   <li><b>rock behind a face is carved</b> — otherwise nothing changed
 *   <li><b>rock under flat ground is not</b> — the same gates keep plains from turning into a
 *       lattice of holes, and the cheap way to pass the first assertion is to open them
 *       everywhere
 * </ul>
 *
 * <p>{@link CliffTileSource} supplies both conditions in one world, so the comparison holds
 * seed, biome and every noise channel fixed and varies only the terrain's steepness. Both
 * populations are flat plateau top at the same height; they differ only in how far they sit
 * from a lip, and therefore only in exposure. That makes the interior columns a live control
 * rather than a second measurement — they are what the exposed columns did before this change,
 * generated by the same code in the same run.
 */
public class CliffCarveDepthTest {

    private static final long SEED = 12345L;
    private static final int CHUNK = WorldConfiguration.CHUNK_SIZE;

    /** Region: 128 blocks of X spans exactly one plateau and one lowland half-period. */
    private static final int REGION_X = 8;
    private static final int REGION_Z = 4;

    /** A column this close to a lip is behind a face; this far from one is flat ground. */
    private static final int EXPOSED_WITHIN = 12;
    private static final int INTERIOR_BEYOND = 22;

    /**
     * The shell this is all about: below {@code OVERHANG_DEPTH}, above where the spaghetti fade
     * reaches full thickness. This is the rock an opening runs into, and measuring it has to
     * start below 16 — inside the overhang band the biome rule carves either way, which is
     * unchanged here and would swamp the comparison with a signal neither column class differs
     * on.
     */
    private static final int BAND_MIN_DEPTH = 17;
    private static final int BAND_MAX_DEPTH = 34;

    /**
     * How much more of that shell must be carved behind a face than under flat ground.
     *
     * <p>Ratchet floor, set just under the measured 2.8x (11.9% against 4.2%). Note this ratio
     * cannot be driven arbitrarily high by tuning the density field: the worms, caverns and
     * ravines carve the shell at a rate that has nothing to do with exposure, and that
     * contribution is in both terms. A large move here means the scatter carvers changed, not
     * that cliffs got better.
     */
    private static final double MIN_EXPOSED_ADVANTAGE = 2.5;

    /**
     * Depth an opening must reach for it to count as having broken into the network rather
     * than merely gone deeper. Past this it is below the whole shell and among the worms, whose
     * origins start 20 blocks down.
     */
    private static final int NETWORK_DEPTH = 40;

    @Test
    public void exposureSeparatesFacesFromFlatGround() {
        CliffExposure exposure = new CliffExposure(new HeightMapGenerator(new CliffTileSource()));

        for (int x = 0; x < CliffTileSource.PERIOD; x++) {
            float e = exposure.exposureAt(x, 40);
            int dist = CliffTileSource.distanceToLip(x);
            if (dist >= INTERIOR_BEYOND) {
                assertEquals(0f, e, 0f, String.format(
                        "column x=%d is %d blocks from the nearest lip and must read as flat "
                                + "ground — a non-zero exposure there means the two carve curves "
                                + "get interpolated where nothing should change", x, dist));
            } else if (dist <= 2 && CliffTileSource.onPlateau(x)) {
                assertTrue(e > 0.9f, String.format(
                        "column x=%d sits on the lip of a %d-block cliff and reads exposure "
                                + "%.3f — the face is not being detected", x,
                        CliffTileSource.CLIFF_HEIGHT, e));
            }
        }
    }

    @Test
    public void carvingBehindAFaceIsDeeperAndReachesTheNetwork() {
        TerrainGenerationSystem terrain =
                new TerrainGenerationSystem(SEED, new CliffTileSource());

        int sizeX = REGION_X * CHUNK;
        int sizeZ = REGION_Z * CHUNK;
        int yCap = CliffTileSource.PLATEAU;

        boolean[] air = new boolean[sizeX * sizeZ * yCap];
        long exposedCarved = 0;
        long exposedTotal = 0;
        long interiorCarved = 0;
        long interiorTotal = 0;

        for (int cx = 0; cx < REGION_X; cx++) {
            for (int cz = 0; cz < REGION_Z; cz++) {
                Chunk chunk = terrain.generateTerrainOnly(cx, cz).chunk();
                for (int lx = 0; lx < CHUNK; lx++) {
                    for (int lz = 0; lz < CHUNK; lz++) {
                        int x = cx * CHUNK + lx;
                        int z = cz * CHUNK + lz;
                        int surface = CliffTileSource.height(x, z);
                        for (int y = 1; y < surface; y++) {
                            if (chunk.getBlock(lx, y, lz) == BlockType.AIR) {
                                air[index(x, y, z, sizeZ, yCap)] = true;
                            }
                        }

                        // Only plateau columns: the lowland floor has no face above it, and
                        // counting it would average the two populations back together.
                        if (!CliffTileSource.onPlateau(x)) {
                            continue;
                        }
                        int dist = CliffTileSource.distanceToLip(x);
                        boolean exposed = dist <= EXPOSED_WITHIN;
                        boolean interior = dist >= INTERIOR_BEYOND;
                        if (!exposed && !interior) {
                            continue;   // transition zone, deliberately unmeasured
                        }
                        for (int d = BAND_MIN_DEPTH; d <= BAND_MAX_DEPTH; d++) {
                            boolean carved = air[index(x, surface - d, z, sizeZ, yCap)];
                            if (exposed) {
                                exposedTotal++;
                                if (carved) {
                                    exposedCarved++;
                                }
                            } else {
                                interiorTotal++;
                                if (carved) {
                                    interiorCarved++;
                                }
                            }
                        }
                    }
                }
            }
        }

        double exposedFraction = exposedCarved / (double) exposedTotal;
        double interiorFraction = interiorCarved / (double) interiorTotal;
        int deepest = deepestReachableFromALip(air, sizeX, sizeZ, yCap);

        System.out.printf("[cliffs] depth %d-%d carved: %.2f%% behind a face vs %.2f%% under "
                        + "flat ground (%.1fx); deepest cell reachable from a lip opening: "
                        + "%d blocks below the plateau%n",
                BAND_MIN_DEPTH, BAND_MAX_DEPTH, exposedFraction * 100, interiorFraction * 100,
                interiorFraction > 0 ? exposedFraction / interiorFraction
                        : Double.POSITIVE_INFINITY,
                deepest);

        assertTrue(exposedFraction >= interiorFraction * MIN_EXPOSED_ADVANTAGE, String.format(
                "rock behind a face is only %.2f%% carved at depth %d-%d against %.2f%% under "
                        + "flat ground — openings still run into a wall",
                exposedFraction * 100, BAND_MIN_DEPTH, BAND_MAX_DEPTH, interiorFraction * 100));

        assertTrue(deepest >= NETWORK_DEPTH, String.format(
                "the deepest cell reachable from an opening in a cliff face is %d blocks below "
                        + "the plateau; it needs to reach %d to have broken into the cave "
                        + "network rather than just made a bigger alcove", deepest, NETWORK_DEPTH));
    }

    /**
     * Deepest point a player entering at a cliff lip can get to, as blocks below the plateau.
     *
     * <p>Flood is 6-connected and confined to cells strictly below their own column's surface.
     * That confinement is the whole point: without it the fill would leave the face into open
     * sky, drop 60 blocks down the outside of the cliff, and report a depth no cave produced.
     */
    private static int deepestReachableFromALip(boolean[] air, int sizeX, int sizeZ, int yCap) {
        int surfaceOf = CliffTileSource.PLATEAU;
        boolean[] seen = new boolean[air.length];
        int[] queue = new int[air.length];
        int head = 0;
        int tail = 0;

        for (int x = 0; x < sizeX; x++) {
            if (!CliffTileSource.onPlateau(x) || CliffTileSource.distanceToLip(x) > 2) {
                continue;
            }
            for (int z = 0; z < sizeZ; z++) {
                for (int y = surfaceOf - 16; y < surfaceOf; y++) {
                    int i = index(x, y, z, sizeZ, yCap);
                    if (air[i] && !seen[i]) {
                        seen[i] = true;
                        queue[tail++] = i;
                    }
                }
            }
        }

        int deepest = 0;
        int[] dx = {1, -1, 0, 0, 0, 0};
        int[] dy = {0, 0, 1, -1, 0, 0};
        int[] dz = {0, 0, 0, 0, 1, -1};
        while (head < tail) {
            int i = queue[head++];
            int y = i % yCap;
            int xz = i / yCap;
            int x = xz / sizeZ;
            int z = xz % sizeZ;
            deepest = Math.max(deepest, surfaceOf - y);
            for (int n = 0; n < 6; n++) {
                int nx = x + dx[n];
                int ny = y + dy[n];
                int nz = z + dz[n];
                if (nx < 0 || nx >= sizeX || nz < 0 || nz >= sizeZ
                        || ny < 1 || ny >= CliffTileSource.height(nx, nz)) {
                    continue;
                }
                int j = index(nx, ny, nz, sizeZ, yCap);
                if (air[j] && !seen[j]) {
                    seen[j] = true;
                    queue[tail++] = j;
                }
            }
        }
        return deepest;
    }

    private static int index(int x, int y, int z, int sizeZ, int yCap) {
        return (x * sizeZ + z) * yCap + y;
    }
}
