package com.stonebreak.world.generation.biomes.modifiers;

import com.stonebreak.world.generation.biomes.BiomeType;
import com.stonebreak.world.generation.noise.MultiNoiseParameters;

/**
 * Interface for biome-specific terrain height modifications.
 *
 * Phase 2 Enhancement: Biome-Specific Height Modifiers
 *
 * This system adds fine-tuned height adjustments AFTER biome selection,
 * allowing biomes to create dramatic terrain features like:
 * - Badlands: Canyon carving and hoodoo/spire generation
 * - Stony Peaks: Vertical amplification and rocky outcrops
 * - Desert: Rolling dune patterns
 *
 * Design Philosophy:
 * - Modifiers apply AFTER terrain hints (two-pass generation)
 * - Should stay within ±20 blocks to maintain terrain consistency
 * - Use noise-based features for organic, natural-looking terrain
 * - Modifiers are optional - not all biomes need them
 *
 * Thread-safe (implementations should be stateless or use thread-safe noise generators).
 */
public interface BiomeTerrainModifier {

    /**
     * Modifies the base terrain height for biome-specific features.
     *
     * This is called AFTER terrain generation in the two-pass system:
     * Pass 1: TerrainGenerator applies multi-noise parameters
     * Pass 2: BiomeTerrainModifier applies biome-specific features
     *
     * Guidelines:
     * - Keep modifications within ±20 blocks for consistency
     * - Use noise for organic, varied features
     * - Consider the multiNoiseParameters for context-aware modifications
     *
     * @param baseHeight The height generated by TerrainGenerator
     * @param params The multi-noise parameters at this location
     * @param x World X coordinate
     * @param z World Z coordinate
     * @return Modified height (should stay within ±20 blocks of baseHeight)
     */
    int modifyHeight(int baseHeight, MultiNoiseParameters params, int x, int z);

    /**
     * Whether this modifier should be applied given the parameters.
     *
     * Allows conditional application based on:
     * - Parameter values (e.g., only apply in high PV areas)
     * - Height thresholds (e.g., only affect mountains above certain height)
     * - Any other context-specific conditions
     *
     * @param params The multi-noise parameters at this location
     * @param baseHeight The base height before modification
     * @return True if modifier should be applied, false to skip
     */
    boolean shouldApplyModifier(MultiNoiseParameters params, int baseHeight);

    /**
     * Get the biome type this modifier applies to.
     *
     * Used by the modifier registry for lookup.
     *
     * @return BiomeType this modifier is designed for
     */
    BiomeType getBiomeType();
}
