package com.stonebreak.ui.terrainmapper.visualization.impl;

import com.stonebreak.ui.terrainmapper.visualization.NoiseVisualizer;
import com.stonebreak.world.generation.config.TerrainGenerationConfig;
import com.stonebreak.world.generation.heightmap.HeightMapGenerator;
import com.stonebreak.world.generation.noise.MultiNoiseParameters;
import com.stonebreak.world.generation.noise.NoiseRouter;
import com.stonebreak.world.operations.WorldConfiguration;

/**
 * Visualizes actual terrain height (elevation) generated by the multi-noise system.
 *
 * This visualizer shows the final terrain height that would be generated at each position,
 * combining all noise parameters (continentalness, erosion, peaks & valleys, weirdness).
 *
 * Unlike parameter visualizers which show individual noise values, this shows the
 * combined result - the actual elevation of the terrain surface.
 *
 * Sampling Process:
 * 1. Sample all 6 parameters via NoiseRouter
 * 2. Generate height from parameters via HeightMapGenerator
 * 3. Return height in range [0, 256] (world height bounds)
 *
 * Visualization:
 * - Black (0.0): Sea level or below
 * - Gray (0.5): Mid-elevation (around height 128)
 * - White (1.0): Maximum elevation (height 256)
 *
 * Thread Safety: Safe for concurrent use (NoiseRouter and HeightMapGenerator are thread-safe)
 */
public class HeightMapVisualizer implements NoiseVisualizer {

    private final NoiseRouter noiseRouter;
    private final HeightMapGenerator heightGenerator;

    /**
     * Creates a new height map visualizer.
     *
     * @param seed World seed for deterministic generation
     * @param config Terrain generation configuration
     */
    public HeightMapVisualizer(long seed, TerrainGenerationConfig config) {
        this.noiseRouter = new NoiseRouter(seed, config);
        this.heightGenerator = new HeightMapGenerator(seed, config);
    }

    /**
     * Samples terrain height at the given world position.
     *
     * Generates the actual elevation that would appear at this position,
     * using the full multi-noise terrain generation system.
     *
     * @param worldX World X coordinate
     * @param worldZ World Z coordinate
     * @param seed World seed (unused - seed already set in constructor)
     * @return Terrain height in range [0, 256]
     */
    @Override
    public double sample(int worldX, int worldZ, long seed) {
        // Sample all 6 parameters at this position
        MultiNoiseParameters params = noiseRouter.sampleParameters(worldX, worldZ);

        // Generate height from parameters
        int height = heightGenerator.generateHeight(worldX, worldZ, params);

        return height;
    }

    /**
     * Gets the display name for this visualizer.
     *
     * @return "Terrain Height"
     */
    @Override
    public String getName() {
        return "Terrain Height";
    }

    /**
     * Gets the minimum possible height (sea level).
     *
     * @return 0.0 (minimum terrain height)
     */
    @Override
    public double getMinValue() {
        return 0.0;
    }

    /**
     * Gets the maximum possible height (world height limit).
     *
     * @return 256.0 (maximum terrain height)
     */
    @Override
    public double getMaxValue() {
        return WorldConfiguration.WORLD_HEIGHT;
    }
}
