package com.openmason.engine.ui.script;

import com.openmason.engine.ui.script.UiApiCatalog.Member;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * LuaLS type stubs for the {@code ui} API (#292), generated from {@link UiApiCatalog}: completion,
 * signatures and type diagnostics for code-behind in any LuaLS editor (VS Code, Neovim, IntelliJ
 * EmmyLua). {@link #write} drops {@code types/ui.d.lua} and a {@code .luarc.json} that turns off the
 * standard libraries the sandbox does not have and allows lowercase globals (environment globals
 * are per-instance state that survives hot reload). Annotate a module table with
 * {@code ---@type ui.Module} so its hooks' {@code ui} parameter is typed too.
 */
public final class UiApiStubs {

    public static final String STUB_FILE = "types/ui.d.lua";
    public static final String CONFIG_FILE = ".luarc.json";

    private static final String[][] CLASSES = {
        {"ui.Element", "Element", "A document element, by stable key. Operations on elements outside the script's scope fail."},
        {"ui.Canvas", "Canvas", "The draw surface of a Canvas element. Commands go straight into a native buffer."},
        {"ui.Handle", "Handle", "An awaitable action call, animation or timer."},
        {"ui.Event", "Event", "A UI event delivered to an element handler or on_input."},
    };

    private UiApiStubs() {
    }

    /** The {@code ui.d.lua} stub text. */
    public static String stub() {
        StringBuilder b = new StringBuilder();
        b.append("---@meta\n");
        b.append("-- Stonebreak UI scripting API, uiApi ").append(UiApiCatalog.VERSION)
            .append(" (#292). Generated by UiApiStubs from UiApiCatalog: do not edit.\n");
        b.append("-- The sandbox has base (no dofile/loadfile/collectgarbage), coroutine, math, string (no dump),\n");
        b.append("-- table and utf8. require() only loads modules the document declares.\n\n");
        for (String[] c : CLASSES) {
            klass(b, c[0], c[1], c[2]);
        }
        b.append("---@class ui.Module\n");
        b.append("---A code-behind module: return a table with any of these hooks, or define them as globals.\n");
        for (Member m : UiApiCatalog.of("module")) {
            b.append("---@field ").append(m.name()).append("? fun(").append(funParams(m.params())).append(")");
            if (!m.returns().isEmpty()) {
                b.append(": ").append(m.returns());
            }
            b.append(" ").append(m.doc()).append('\n');
        }
        b.append('\n');
        b.append("---The ui API of this script's document (scoped to its component instance in a component).\n");
        b.append("---@class ui\n");
        for (Member m : UiApiCatalog.of("ui")) {
            if (m.field()) {
                b.append("---@field ").append(m.name()).append(' ').append(m.returns()).append(' ')
                    .append(m.doc()).append('\n');
            }
        }
        b.append("ui = {}\n\n");
        for (Member m : UiApiCatalog.of("ui")) {
            if (!m.field()) {
                function(b, "ui." + m.name(), m);
            }
        }
        return b.toString();
    }

    /** The {@code .luarc.json} next to the scripts. */
    public static String luarc() {
        return """
            {
              "$schema": "https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json",
              "runtime.version": "Lua 5.4",
              "runtime.builtin": {
                "debug": "disable",
                "io": "disable",
                "os": "disable",
                "package": "disable"
              },
              "workspace.library": [
                "types"
              ],
              "diagnostics.disable": [
                "lowercase-global"
              ],
              "diagnostics.globals": [
                "on_open",
                "on_close",
                "update",
                "on_input",
                "on_reload"
              ]
            }
            """;
    }

    /** Writes the stub and the LuaLS config under {@code dir} (a project's script folder). */
    public static void write(Path dir) throws IOException {
        Path stub = dir.resolve(STUB_FILE);
        Files.createDirectories(stub.getParent());
        Files.writeString(stub, stub(), StandardCharsets.UTF_8);
        Files.writeString(dir.resolve(CONFIG_FILE), luarc(), StandardCharsets.UTF_8);
    }

    private static void klass(StringBuilder b, String type, String local, String doc) {
        b.append("---").append(doc).append('\n');
        b.append("---@class ").append(type).append('\n');
        for (Member m : UiApiCatalog.of(type)) {
            if (m.field()) {
                b.append("---@field ").append(m.name()).append(' ').append(m.returns());
                if (!m.doc().isEmpty()) {
                    b.append(' ').append(m.doc());
                }
                b.append('\n');
            }
        }
        b.append("local ").append(local).append(" = {}\n\n");
        for (Member m : UiApiCatalog.of(type)) {
            if (!m.field()) {
                function(b, local + ":" + m.name(), m);
            }
        }
    }

    private static void function(StringBuilder b, String qualified, Member m) {
        if (!m.doc().isEmpty()) {
            b.append("---").append(m.doc()).append('\n');
        }
        List<String> names = new ArrayList<>();
        for (String p : split(m.params())) {
            String name;
            String type;
            if (p.startsWith("...")) {
                name = "...";
                type = p.length() > 3 ? p.substring(3) : "any";
            } else {
                int sp = p.indexOf(' ');
                name = sp < 0 ? p : p.substring(0, sp);
                type = sp < 0 ? "any" : p.substring(sp + 1).trim();
            }
            boolean optional = type.endsWith("?");
            if (optional) {
                type = type.substring(0, type.length() - 1);
            }
            b.append("---@param ").append(name).append(optional ? "? " : " ").append(type).append('\n');
            names.add(name);
        }
        for (String r : split(m.returns())) {
            b.append("---@return ").append(r).append('\n');
        }
        b.append("function ").append(qualified).append('(').append(String.join(", ", names)).append(") end\n\n");
    }

    /** {@code name type, name type} → {@code name: type, name: type} for a fun() type. */
    private static String funParams(String params) {
        List<String> out = new ArrayList<>();
        for (String p : split(params)) {
            int sp = p.indexOf(' ');
            out.add(sp < 0 ? p : p.substring(0, sp) + ": " + p.substring(sp + 1).trim());
        }
        return String.join(", ", out);
    }

    /** Splits on commas outside brackets, braces and parentheses. */
    static List<String> split(String s) {
        List<String> out = new ArrayList<>();
        int depth = 0;
        int start = 0;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '(' || c == '{' || c == '<' || c == '[') {
                depth++;
            } else if (c == ')' || c == '}' || c == '>' || c == ']') {
                depth--;
            } else if (c == ',' && depth == 0) {
                add(out, s.substring(start, i));
                start = i + 1;
            }
        }
        add(out, s.substring(start));
        return out;
    }

    private static void add(List<String> out, String part) {
        String t = part.trim();
        if (!t.isEmpty()) {
            out.add(t);
        }
    }
}
